CREATE TABLE users (
    user_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_BUYER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_role CHECK (role IN ('ROLE_BUYER', 'ROLE_SELLER', 'ROLE_MANAGER', 'ROLE_ADMIN'))
);

ALTER TABLE customers
    ADD COLUMN user_id BIGINT UNSIGNED NOT NULL UNIQUE default 1,
    ADD CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;